name: Build and push Docker image Postgres v13, Spilo 2.1-p1, Timescale 2.4.1

on: workflow_dispatch

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          ref: 2.1-p1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v2
        with:
          images: phlegx/spilo-13

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./postgres-appliance
          push: true
          tags: latest,2.1-p1
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            PGVERSION=13
            TIMESCALEDB_APACHE_ONLY=false
